[workspace]
members = [
    "core",
    "messages",
    "store_lmdb",
    "ledger",
    "node",
    "ffi",
    "main",
    "tools/load_test",
    "tools/xtask",
    "tools/test_helpers",
    "rpc",
]
resolver = "2"
