[package]
name = "nanospam"
version = "0.1.0"
edition = "2024"

[features]
rai_protocol = [
    "rsnano_types/rai_protocol",
    "rsnano_messages/rai_protocol",
    "rsnano_network/rai_protocol",
    "rsnano_network_protocol/rai_protocol",
]

[dependencies]
rsnano_nullable_clock = { path = "../../nullables/clock" }
rsnano_nullable_tcp = { path = "../../nullables/tcp" }
rsnano_nullable_tracing_subscriber = { path = "../../nullables/tracing_subscriber" }
rsnano_nullable_env = { path = "../../nullables/env" }
rsnano_types = { path = "../../types" }
rsnano_utils = { path = "../../utils" }
rsnano_messages = { path = "../../messages" }
rsnano_network = { path = "../../network" }
rsnano_network_protocol = { path = "../../network_protocol" }
rsnano_websocket_messages = { path = "../../websocket/messages" }
rsnano_websocket_client = { path = "../../websocket/client" }
rsnano_rpc_client = { path = "../../rpc/client" }
rsnano_rpc_messages = { path = "../../rpc/messages" }
anyhow = "1.0.102"
futures = "0.3"
tokio = { version = "1.52.3", features = ["macros", "rt", "rt-multi-thread", "net", "io-util", "signal"] }
tokio-scoped = "0.2.0"
tracing = "0.1.44"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.10.1"
tokio-util = "0.7.18"
dirs = "6.0.0"
clap = { version = "4.6.1", features = ["derive"] }
rustc-hash = "2.1.2"
num-format = "0.4.4"

[dev-dependencies]
ntest = "0.9.5"
