[package]
name = "test_helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_core = { path = "../../core" }
rsnano_network = { path = "../../network" }
rsnano_node = { path = "../../node", features = ["output_tracking"] }
rsnano_nullable_tcp = { path = "../../nullables/tcp" }
mock_instant = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
axum = "0"
tracing-test = "0"
