[package]
name = "test_helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_core = { path = "../../core" }
rsnano_node = { path = "../../node", features = ["output_tracking"] }
rsnano_rpc = { path = "../../rpc" }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
reqwest = { version = "0.11.7", default-features = false, features = ["json"] }
serde_json = "1"
tokio = { version = "1", features = ["net"] }
anyhow = "1.0.40"
