name: Unit Tests

on: [push, pull_request]

env:
  RELEASE: 0
  artifact: 0

jobs:
  osx_test:
    name: macOS
    strategy:
      fail-fast: false
      matrix:
        RELEASE:
          - ${{ startsWith(github.ref, 'refs/tags/') }}
    env:
      RELEASE: ${{ matrix.RELEASE }}
    runs-on: macos-12
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Fetch Deps
        run: TEST=1 ci/actions/osx/install_deps.sh

      - name: Build Tests
        run: ci/build-ci.sh "/tmp/qt/lib/cmake/Qt5";

      - name: Run Tests
        run: cd build && sudo RUST_BACKTRACE=1 ../ci/test.sh .

  linux_test:
    name: Linux [${{ matrix.COMPILER }}]
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        COMPILER: [gcc, clang]
        RELEASE:
          - ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-22.04
    env:
      COMPILER: ${{ matrix.COMPILER }}
      RELEASE: ${{ matrix.RELEASE }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh

      - name: Build Tests
        run: docker run -e RELEASE -v ${PWD}:/workspace simpago/rsnano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace && ./ci/build-ci.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5"
      - name: Run Tests
        run: docker run -e RELEASE -e RUST_BACKTRACE=1 -v ${PWD}:/workspace simpago/rsnano-env:${{ matrix.COMPILER }} /bin/bash -c "cd /workspace/build && ../ci/test.sh ."

